import type {GetStaticProps, NextPage} from 'next'
import Head from 'next/head'
import Header from 'components/shared/Header';
import Footer from 'components/shared/Footer';
import Hero from "components/Hero";
import About from "components/About";
import WorkExperience from "components/WorkExperience";
import Skills from "components/Skills";
import Projects from "components/Projects";
import Contact from "components/Contact";
import {Project, Social, Experience, Skill, PageInfo} from 'typings';
import {fetchPageInfo} from "utils/fetchPageInfo";
import {fetchProjects} from "utils/fetchProjects";
import {fetchSkills} from "utils/fetchSkills";
import {fetchExperience} from "utils/fetchExperience";
import {fetchSocials} from "utils/fetchSocials";

type Props = {
  pageInfo: PageInfo[];
  projects: Project[];
  skills: Skill[];
  experiences: Experience[];
  socials: Social[];
}

const Home: NextPage = ({pageInfo, projects, skills, experiences, socials}: Props) => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y  overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-gray-400/20 scrollbar-thumb-[#F7AB0A]/80 scrollbar-thin'>
      <Head>
        <title>Alex Rodriguez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header socials={socials} />
      <Hero pageInfo={pageInfo} />
      <About pageInfo={pageInfo} />
      <WorkExperience experiences={experiences} />
      <Skills skills={skills} />
      <Projects projects={projects} />
      <Contact />

      {/*<Footer />*/}


    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps<Props> = async () => {
  const pageInfo: PageInfo[] = await fetchPageInfo();
  const projects: Project[] = await fetchProjects();
  const skills: Skill[] = await fetchSkills();
  const experiences: Experience[] = await fetchExperience();
  const socials: Social[] = await fetchSocials();

  return {
    props: {
      pageInfo,
      projects,
      skills,
      experiences,
      socials
    },
    revalidate: 10
  }
}
