import type { NextPage } from 'next'
import Head from 'next/head'
import Header from 'components/shared/Header';
import Footer from 'components/shared/Footer';
import Hero from "components/Hero";
import About from "components/About";

const Home: NextPage = () => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll z-0'>
      <Head>
        <title>Alex Rodriguez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <About />
      <h1 className="text-3xl font-bold underline hover:text-cyan-600 ">
        Hello world!
      </h1>
      <Footer />


    </div>
  )
}

export default Home
